### ISSUE TITLE
Lmod 7 dictionary keys

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#111]
in Lmod 7 the dictionary have different key names such as `fullName`, `parentAA` as pose to Lmod 6.
Here is an example from Lmod 7 dictionary when running ` $LMOD_DIR/spider -o spider-json $MODULEPATH | python -m json.tool`

```
"ifort": {
        "/gpfs/apps/easybuild/2019/SkyLake/redhat/7.5/modules/all/ifort/2018.3.222-GCC-7.3.0-2.30.lua": {
            "pV": "000002018.000000003.000000222.*gcc.*zfinal-.000000007.000000003.*zfinal-.000000002.000000030.*zfinal",
            "Description": "Intel Fortran compiler",
            "pathA": {
                "/gpfs/apps/easybuild/2019/SkyLake/redhat/7.5/software/ifort/2018.3.222-GCC-7.3.0-2.30/compilers_and_libraries_2018.3.222/linux/bin/intel64": 1
            },
            "lpathA": {
                "/gpfs/apps/easybuild/2019/SkyLake/redhat/7.5/software/ifort/2018.3.222-GCC-7.3.0-2.30/debugger_2018/libipt/intel64/lib": 1,
                "/gpfs/apps/easybuild/2019/SkyLake/redhat/7.5/software/ifort/2018.3.222-GCC-7.3.0-2.30/compilers_and_libraries_2018.3.222/linux/compiler/lib/intel64": 1
            },
            "wV": "000002018.000000003.000000222.*gcc.*zfinal-.000000007.000000003.*zfinal-.000000002.000000030.*zfinal",
            "help": "\nDescription\n===========\nIntel Fortran compiler\n\n\nMore information\n================\n - Homepage: http://software.intel.com/en-us/intel-compilers/\n",
            "parentAA": [
                [
                    "eb/2019"
                ]
            ],
            "hidden": false,
            "fullName": "ifort/2018.3.222-GCC-7.3.0-2.30",
            "Version": "2018.3.222-GCC-7.3.0-2.30",
            "whatis": [
                "Description: Intel Fortran compiler",
                "Homepage: http://software.intel.com/en-us/intel-compilers/"
            ]
        }
    }

```

buildtest is unable to find key `full` and the error is the following
```
(buildtest-framework) [siddis14@delta-login1 buildtest-framework]$ buildtest --help
Traceback (most recent call last):
  File "/gpfs/apps/medsci/stacks/2/adhoc/anaconda3/5.3.0/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/gpfs/apps/medsci/stacks/2/adhoc/anaconda3/5.3.0/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/gpfs/home/siddis14/buildtest-framework/src/main.py", line 62, in <module>
    main()
  File "/gpfs/home/siddis14/buildtest-framework/src/main.py", line 45, in main
    parser = menu()
  File "./src/buildtest/tools/menu.py", line 68, in menu
    module_stack = module_obj.get_unique_software_modules()
  File "./src/buildtest/tools/modules.py", line 104, in get_unique_software_modules
    software_set.add(self.module_dict[k][mod_file]["full"])
KeyError: 'full'
```
This was tested in the following version
```
buildtest-framework) [siddis14@delta-login1 buildtest-framework]$ module --version

Modules based on Lua: Version 7.7.14  2017-11-16 16:23 -07:00
    by Robert McLay mclay@tacc.utexas.edu
```

**Comment by shahzebsiddiqui** [comment]
fixed in https://github.com/HPC-buildtest/buildtest-framework/commit/a42521c7759edc183d7cbd6d612b226e27c1e233
