### ISSUE TITLE
issue with dry run.

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#230]
Capturing this error during dry run, i know how to fix it. 
```
(docs) login1.stampede2(1098)$ buildtest build -d -c examples/script/bzip2.yml
________________________________________________________________________________
                             start time: 2020-03-19 15:10:09.612431
                     configuration file: /work/06908/sms1990/stampede2/buildtest-framework/examples/script/bzip2.yml
                                testdir: /home1/06908/sms1990/.buildtest/testdir/bzip_compression
                               testpath: /home1/06908/sms1990/.buildtest/testdir/bzip_compression/bzip_compression_03-19-2020-15-10.csh
                                logpath: None
________________________________________________________________________________



STAGE                                    VALUE
________________________________________________________________________________
#!/bin/csh
cd $TESTDIR
setenv FILE 1mb_bzip2.txt
setenv TARFILE 1mb_bzip2.txt.bz2
dd if=/dev/zero of="$FILE" bs=1M count=1
tar cvjf "$TARFILE" "$FILE"
ls -l "$TARFILE"

Traceback (most recent call last):
  File "/home1/06908/sms1990/.local/share/virtualenvs/docs-qbK3SfF3/bin/buildtest", line 11, in <module>
    load_entry_point('buildtest-framework', 'console_scripts', 'buildtest')()
  File "/work/06908/sms1990/stampede2/buildtest-framework/buildtest/main.py", line 20, in main
    parser.parse_options()
  File "/work/06908/sms1990/stampede2/buildtest-framework/buildtest/menu/__init__.py", line 81, in parse_options
    args.func(args)
  File "/work/06908/sms1990/stampede2/buildtest-framework/buildtest/menu/build.py", line 118, in func_build_subcmd
    BUILDTEST_BUILD_HISTORY[result["BUILD_ID"]] = result
TypeError: 'NoneType' object is not subscriptable
```

**Comment by shahzebsiddiqui** [comment]
The issue is fixed in #229 

```
(docs) login1.stampede2(1099)$ buildtest build -d -c examples/script/bzip2.yml
________________________________________________________________________________
                             start time: 2020-03-19 15:13:36.494767
                     configuration file: /work/06908/sms1990/stampede2/buildtest-framework/examples/script/bzip2.yml
                                testdir: /home1/06908/sms1990/.buildtest/testdir/bzip_compression
                               testpath: /home1/06908/sms1990/.buildtest/testdir/bzip_compression/bzip_compression_03-19-2020-15-13.csh
                                logpath: None
________________________________________________________________________________



STAGE                                    VALUE
________________________________________________________________________________
#!/bin/csh
cd $TESTDIR
setenv FILE 1mb_bzip2.txt
setenv TARFILE 1mb_bzip2.txt.bz2
dd if=/dev/zero of="$FILE" bs=1M count=1
tar cvjf "$TARFILE" "$FILE"
ls -l "$TARFILE"

```
