### ISSUE TITLE
documentation build failure

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#247]
apparenty buildtest docs are not building  for 1 week now 

![image](https://user-images.githubusercontent.com/12942230/77830311-040a2800-70fe-11ea-8e7f-debf2c06cc40.png)

see https://readthedocs.org/projects/buildtest/builds/10708692/

```
Running Sphinx v2.4.3

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/buildtest/envs/devel/lib/python3.6/site-packages/sphinx/config.py", line 348, in eval_config_file
    execfile_(filename, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/buildtest/envs/devel/lib/python3.6/site-packages/sphinx/util/pycompat.py", line 81, in execfile_
    exec(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/buildtest/checkouts/devel/docs/conf.py", line 19, in <module>
    from buildtest import BUILDTEST_VERSION
ModuleNotFoundError: No module named 'buildtest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/buildtest/envs/devel/lib/python3.6/site-packages/sphinx/cmd/build.py", line 275, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/buildtest/envs/devel/lib/python3.6/site-packages/sphinx/application.py", line 219, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/buildtest/envs/devel/lib/python3.6/site-packages/sphinx/config.py", line 193, in read
    namespace = eval_config_file(filename, tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/buildtest/envs/devel/lib/python3.6/site-packages/sphinx/config.py", line 358, in eval_config_file
    raise ConfigError(msg % traceback.format_exc())
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/buildtest/envs/devel/lib/python3.6/site-packages/sphinx/config.py", line 348, in eval_config_file
    execfile_(filename, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/buildtest/envs/devel/lib/python3.6/site-packages/sphinx/util/pycompat.py", line 81, in execfile_
    exec(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/buildtest/checkouts/devel/docs/conf.py", line 19, in <module>
    from buildtest import BUILDTEST_VERSION
ModuleNotFoundError: No module named 'buildtest'


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/buildtest/envs/devel/lib/python3.6/site-packages/sphinx/config.py", line 348, in eval_config_file
    execfile_(filename, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/buildtest/envs/devel/lib/python3.6/site-packages/sphinx/util/pycompat.py", line 81, in execfile_
    exec(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/buildtest/checkouts/devel/docs/conf.py", line 19, in <module>
    from buildtest import BUILDTEST_VERSION
ModuleNotFoundError: No module named 'buildtest'

```

Will get this fixed right away.

**Comment by shahzebsiddiqui** [comment]
The fix in #248 fixed the issue in readthedocs. See build https://readthedocs.org/projects/buildtest/builds/10714504/
