### ISSUE TITLE
slurm key error when testing on stampede2

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#336]
```
+----------------------+
| Stage: Running Test  |
+----------------------+ 

Name                 Executor             Status               Return Code          Buildspec Path      
________________________________________________________________________________________________________________________
hello_c_openmp       local.bash           FAIL                 127                  /tmp/repo/github.com/buildtesters/buildtest-stampede2/tests/apps/openmp/hello.yml
[job_test]: Polling Job 5952044 in  15 seconds
Job 5952044 in FAILED
 state for test: job_test
Traceback (most recent call last):
  File "/home1/06908/sms1990/.local/share/virtualenvs/buildtest-framework-AeH_CFst/bin/buildtest", line 11, in <module>
    load_entry_point('buildtest-framework', 'console_scripts', 'buildtest')()
  File "/work/06908/sms1990/stampede2/buildtest-framework/buildtest/main.py", line 35, in main
    func_build_subcmd(args, buildtest_configuration)
  File "/work/06908/sms1990/stampede2/buildtest-framework/buildtest/menu/build.py", line 311, in func_build_subcmd
    result = executor.run(builder)
  File "/work/06908/sms1990/stampede2/buildtest-framework/buildtest/executors/base.py", line 125, in run
    executor.gather()
  File "/work/06908/sms1990/stampede2/buildtest-framework/buildtest/executors/base.py", line 536, in gather
    self.result["returncode"] = job_data["ExitCode"].split(":")[0]
KeyError: 'ExitCode'

```

**Comment by shahzebsiddiqui** [comment]
resolved in #344
