### ISSUE TITLE
buildtest-framework pypi package doesn't work

### ISSUE THREAD

**Issue by frobnitzem** [buildtesters/buildtest#729]
**Describe the bug**
pip3 install doesn't work with any releases past `buildtest-framework-0.2.2`.
Installed on OSX running Python 3.9.2

**To Reproduce**

```
$ pip3 install buildtest-framework
Collecting buildtest-framework
  Downloading buildtest-framework-0.6.3.tar.gz (45 kB)
     |████████████████████████████████| 45 kB 1.5 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@3.9/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/q7/dxctxdc16yxc8ms51wyxwddrwxqnlb/T/pip-install-noxpqb1l/buildtest-framework_359cacfe4f044ac3ba7af070bfdb9298/setup.py'"'"'; __file__='"'"'/private/var/folders/q7/dxctxdc16yxc8ms51wyxwddrwxqnlb/T/pip-install-noxpqb1l/buildtest-framework_359cacfe4f044ac3ba7af070bfdb9298/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/q7/dxctxdc16yxc8ms51wyxwddrwxqnlb/T/pip-pip-egg-info-aoqjzgsc
         cwd: /private/var/folders/q7/dxctxdc16yxc8ms51wyxwddrwxqnlb/T/pip-install-noxpqb1l/buildtest-framework_359cacfe4f044ac3ba7af070bfdb9298/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/q7/dxctxdc16yxc8ms51wyxwddrwxqnlb/T/pip-install-noxpqb1l/buildtest-framework_359cacfe4f044ac3ba7af070bfdb9298/setup.py", line 29, in <module>
        from buildtest.tools.config import BUILDTEST_VERSION
      File "/private/var/folders/q7/dxctxdc16yxc8ms51wyxwddrwxqnlb/T/pip-install-noxpqb1l/buildtest-framework_359cacfe4f044ac3ba7af070bfdb9298/buildtest/tools/config.py", line 53, in <module>
        fd = open(BUILDTEST_CONFIG_FILE,'r')
    FileNotFoundError: [Errno 2] No such file or directory: '$HOME/.local/buildtest/config.yaml'
    [Errno 2] No such file or directory: '$HOME/.local/buildtest/config.yaml'
    ----------------------------------------
```

**Expected behavior**
There should be a guard in case the file is not present.

**Comment by shahzebsiddiqui** [comment]
hi @frobnitzem that is very outdated installation guide. buildtest used to publish to pypi but now we just need to clone buildtest and source setup script. See https://buildtest.readthedocs.io/en/devel/installing_buildtest.html

This should fix the issue. Please let me know if you run into any issue for installation.

**Comment by shahzebsiddiqui** [comment]
hi @frobnitzem were you able to get pass this issue. Let me know if you need any further help.

**Comment by shahzebsiddiqui** [comment]
@frobnitzem I assume this is working for you now, if you need any help feel free to reopen this issue.
