### ISSUE TITLE
[Bug]: SameFileError when running multiple tests

### ISSUE THREAD

**Issue by croodm** [buildtesters/buildtest#840]
### Bug Description

I have some insight about the initial issue I had brought up about the SameFileError: it only occurs when multiple tests are ran at the same time. For example, I can run each of these tests separately and they work fine, but there is an issue when I try to do all three together (error message pasted in the "Relevant log output").

Here is the buildspec that raised the issue, though it may be more efficient to create one that does a "Hello world":
```version: "1.0"
buildspecs:
  abaqus_thermal:
    type: script
    executor: sawtooth.pbs.router
    description: Abaqus CFD Software
    tags: [benchmark, sawtooth, openmpi, abaqus, thermal]
    pbs:
     - "-l walltime=00:10:00"
     - "-l select=1:ncpus=1:mpiprocs=1"
    run: |
      module load openmpi/4.0.5_ucx1.9
      module load ABAQUS/2021hf6
      module load python/3.8-anaconda-2020.07
      source activate py2
      export MV2_ENABLE_AFFINITY=0
      mpirun -np 1 python /projects/hpc_intern/tests/sawtooth/abaqus/run_vnv.py -exe abq673 -thermal
  abaqus_standard:
    type: script
    executor: sawtooth.pbs.router
    description: Abaqus CFD Software
    tags: [benchmark, sawtooth, openmpi, abaqus, standard]
    pbs:
     - "-l walltime=00:10:00"
     - "-l select=1:ncpus=1:mpiprocs=1"
    run: |
      module load openmpi/4.0.5_ucx1.9
      module load ABAQUS/2021hf6
      module load python/3.8-anaconda-2020.07
      source activate py2
      export MV2_ENABLE_AFFINITY=0
      mpirun -np 1 python /projects/hpc_intern/tests/sawtooth/abaqus/run_vnv.py -exe abq673 -standard
  abaqus_explicit:
    type: script
    executor: sawtooth.pbs.router
    description: Abaqus CFD Software
    tags: [benchmark, sawtooth, openmpi, abaqus, explicit]
    pbs:
     - "-l walltime=00:10:00"
     - "-l select=1:ncpus=1:mpiprocs=1"
    run: |
      module load openmpi/4.0.5_ucx1.9
      module load ABAQUS/2021hf6
      module load python/3.8-anaconda-2020.07
      source activate py2
      export MV2_ENABLE_AFFINITY=0
      mpirun -np 1 python /projects/hpc_intern/tests/sawtooth/abaqus/run_vnv.py -exe abq673 -explicit```

### Version

devel

### Relevant log output

```shell
Polling Jobs in 12 seconds
________________________________________
Job Queue: ['5351903.sawtoothpbs', '5351904.sawtoothpbs', '5351905.sawtoothpbs']
Pending Jobs
________________________________________
+-----------------+---------------------+---------------------+----------+
|      name       |      executor       |        jobID        | jobstate |
+-----------------+---------------------+---------------------+----------+
| abaqus_thermal  | sawtooth.pbs.router | 5351903.sawtoothpbs |    Q     |
| abaqus_standard | sawtooth.pbs.router | 5351904.sawtoothpbs |    Q     |
| abaqus_explicit | sawtooth.pbs.router | 5351905.sawtoothpbs |    Q     |
+-----------------+---------------------+---------------------+----------+
Polling Jobs in 12 seconds
________________________________________
Job Queue: ['5351903.sawtoothpbs', '5351904.sawtoothpbs', '5351905.sawtoothpbs']
Pending Jobs
________________________________________
+-----------------+---------------------+---------------------+----------+
|      name       |      executor       |        jobID        | jobstate |
+-----------------+---------------------+---------------------+----------+
| abaqus_thermal  | sawtooth.pbs.router | 5351903.sawtoothpbs |    F     |
| abaqus_standard | sawtooth.pbs.router | 5351904.sawtoothpbs |    F     |
| abaqus_explicit | sawtooth.pbs.router | 5351905.sawtoothpbs |    F     |
+-----------------+---------------------+---------------------+----------+
Polling Jobs in 12 seconds
________________________________________
Job Queue: ['5351904.sawtoothpbs']
Completed Jobs
________________________________________
+-----------------+---------------------+---------------------+----------+
|      name       |      executor       |        jobID        | jobstate |
+-----------------+---------------------+---------------------+----------+
| abaqus_thermal  | sawtooth.pbs.router | 5351903.sawtoothpbs |    F     |
| abaqus_explicit | sawtooth.pbs.router | 5351905.sawtoothpbs |    F     |
+-----------------+---------------------+---------------------+----------+
Pending Jobs
________________________________________
+-----------------+---------------------+---------------------+----------+
|      name       |      executor       |        jobID        | jobstate |
+-----------------+---------------------+---------------------+----------+
| abaqus_standard | sawtooth.pbs.router | 5351904.sawtoothpbs |    F     |
+-----------------+---------------------+---------------------+----------+
Polling Jobs in 12 seconds
________________________________________
Traceback (most recent call last):
  File "/projects/hpc_intern/buildtest/bin/buildtest", line 17, in <module>
    buildtest.main.main()
  File "/projects/hpc_intern/buildtest/buildtest/main.py", line 76, in main
    cmd.build()
  File "/projects/hpc_intern/buildtest/buildtest/cli/build.py", line 570, in build
    self.builders = self.run_phase()
  File "/projects/hpc_intern/buildtest/buildtest/cli/build.py", line 870, in run_phase
    valid_builders = self.poll_jobs(poll_queue, valid_builders)
  File "/projects/hpc_intern/buildtest/buildtest/cli/build.py", line 1075, in poll_jobs
    builder_queue = self.buildexecutor.poll(poll_queue)
  File "/projects/hpc_intern/buildtest/buildtest/executors/setup.py", line 277, in poll
    executor.gather(builder)
  File "/projects/hpc_intern/buildtest/buildtest/executors/pbs.py", line 150, in gather
    builder.post_run_steps()
  File "/projects/hpc_intern/buildtest/buildtest/buildsystem/base.py", line 710, in post_run_steps
    self.copy_stage_files()
  File "/projects/hpc_intern/buildtest/buildtest/buildsystem/base.py", line 307, in copy_stage_files
    shutil.copy2(
  File "/apps/local/anaconda/3.8/lib/python3.8/shutil.py", line 432, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/apps/local/anaconda/3.8/lib/python3.8/shutil.py", line 241, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: '/projects/hpc_intern/buildtest/var/tests/sawtooth.pbs.router/abaqus/abaqus_standard/0/abaqus_standard.o5351904' and '/projects/hpc_intern/buildtest/var/tests/sawtooth.pbs.router/abaqus/abaqus_standard/0/abaqus_standard.o5351904' are the same file
```

### Reproduce Bug

```bash
1. Create a buildspec with three different queues that submits to PBS 
2. Run the buildspec such that all three tests are queued
3. The error will occur after the tests are completed
...
```

### Post question in Slack

- [X] I agree that I posted my question in [slack](https://hpcbuildtest.slack.com/) before creating this issue

### Is there an existing issue

- [X] I confirm there is no existing [issue](https://github.com/buildtesters/buildtest/issues) for this issue

**Comment by shahzebsiddiqui** [comment]
@croodm i have a hotfix for this issue in this PR: https://github.com/buildtesters/buildtest/pull/841
