### ISSUE TITLE
issue with sphinx-argparse in readthedocs project build 

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#93]
See build https://readthedocs.org/projects/buildtest/builds/8669213/

The issue is importing buildtest modules in readthedocs due to environment setup

Getting errors like

```
WARNING: autodoc: failed to import module 'benchmark' from module 'buildtest.benchmark'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/buildtest/envs/latest/lib/python3.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/buildtest/checkouts/latest/src/buildtest/benchmark/benchmark.py", line 24, in <module>
    from buildtest.benchmark.osu import run_osu_microbenchmark, list_osu_tests, osu_info
  File "/home/docs/checkouts/readthedocs.org/user_builds/buildtest/checkouts/latest/src/buildtest/benchmark/osu.py", line 31, in <module>
    from buildtest.tools.config import config_opts
  File "/home/docs/checkouts/readthedocs.org/user_builds/buildtest/checkouts/latest/src/buildtest/tools/config.py", line 51, in <module>
    DEFAULT_CONFIG_FILE = os.path.join(os.getenv("BUILDTEST_ROOT"),"settings.yml")
  File "/home/docs/checkouts/readthedocs.org/user_builds/buildtest/envs/latest/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

This causes the documentation for https://buildtest.readthedocs.io/en/latest/command_reference.html to not show any buildtest methods.

When building documentation locally the command reference page is generated properly.

![image](https://user-images.githubusercontent.com/12942230/53581971-97180d80-3b4c-11e9-8a91-8fe23cad5c01.png)

**Comment by shahzebsiddiqui** [comment]
this issue is not relevant. Closing task
